### ISSUE TITLE
Add build for CentOS 8/Stream on copr

### ISSUE THREAD

**Issue by stenstorp** [lkiesow/intellij-idea-community-rpm#1]
I'd like to use your Copr repository for Intellij Idea on CentOS 8. Would you be able to add epel-8 and centos-stream to the list of chroots on your Copr repository?
I can confirm that the rpm builds and runs as expected on these distributions without any modification.

**Comment by lkiesow** [comment]
Sorry, missed this issue. I've just added epel8 and [launched an initial build](https://copr.fedorainfracloud.org/coprs/lkiesow/intellij-idea-community/build/2069396/). If this works, I will leave it in, so you get future updates.

**Comment by lkiesow** [comment]
Builds were successful. Closing this issue.
