### ISSUE TITLE
Transaction error in upgrade from Fedora 34 to Fedora 35

### ISSUE THREAD

**Issue by devinrsmith** [lkiesow/intellij-idea-community-rpm#2]
In the process of upgrading a system from Fedora 34 to Fedora 35, I'm getting a libc.so transaction check error:

```
$ sudo dnf system-upgrade download --refresh --releasever=35
...
Running transaction check
Error: transaction check vs depsolve:
libc.so.6 is needed by intellij-idea-community-2021.2.3-2.fc35.x86_64
libc.so.6(GLIBC_2.0) is needed by intellij-idea-community-2021.2.3-2.fc35.x86_64
libc.so.6(GLIBC_2.1.3) is needed by intellij-idea-community-2021.2.3-2.fc35.x86_64
libc.so.6(GLIBC_2.3.2) is needed by intellij-idea-community-2021.2.3-2.fc35.x86_64
libc.so.6(GLIBC_2.4) is needed by intellij-idea-community-2021.2.3-2.fc35.x86_64
To diagnose the problem, try running: 'rpm -Va --nofiles --nodigest'.
You probably have corrupted RPMDB, running 'rpm --rebuilddb' might fix the issue.
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
```

The diagnostic / repair commands suggested provide no additional information.

I'm a bit out of my depth trying to solve package manager transaction errors - if you have any insight, it would be much appreciated. Otherwise, I'll probably take the route of uninstalling the package, upgrading, and trying to re-install. Thanks.

**Comment by lkiesow** [comment]
Interesting. I have already migrated from Fedora 34 to 35 a while ago. I'm running intellij-idea-community `2021.2.3-2.fc35` with no complaints. I still have a F34 device though. I'll try migrating that sometime this week to check if I can reproduce the problem.

Does the issue cause your update to fail completely?

**Comment by devinrsmith** [comment]
I haven't tried the `system-upgrade reboot` command, given that the `system-upgrade download` transaction check is failing (exit code 1). I'm playing it safe and will retry to upgrade Friday (so I can have the full weekend to fix if something breaks...).

**Comment by lkiesow** [comment]
Okay, I'll today or tomorrow. I'll let you know how things go.

**Comment by devinrsmith** [comment]
For reference, I'm currently at `intellij-idea-community-2021.2.3-2.fc34.x86_64`

**Comment by lkiesow** [comment]
Did check this on my laptop, and the good/bad news is that I can reproduce the issue. It's weird that this shows during the update but not in the final Fedora 35. That means a workaround is probably to remove IntelliJ, upgrade and then re-install it.

But I'm looking into the issue right now and can hopefully fix the problem. Let's see…

**Comment by lkiesow** [comment]
I managed to fix the issue. Please try again. `dnf system-upgrade` should complain no longer.
Also, 2021.3 is out and is being built right now.
Let me know if the upgrade now works for you.

**Comment by devinrsmith** [comment]
Thanks in advanced for the work! I'll continue with the upgrade tonight, and report back.

**Comment by devinrsmith** [comment]
Upgrade success, thanks for the quick fix!
