### ISSUE TITLE
Preview for Markdown doesn't work, preview for AsciiDoc is limited

### ISSUE THREAD

**Issue by ahus1** [lkiesow/intellij-idea-community-rpm#4]
When installing the this on Fedora 36, this installs IntelliJ Community without the JRE runtime. When starting the IDE it will use either a Java version that is installed on Fedora, or any other Java version the user has on their path. 

This leads to a IDE installation that can't use JCEF or JavaFX based previews. The JCEF preview is needed for example for JetBrains's Markdown plugin. This has previously been reported in #3. 

It is also used by the AsciiDoc plugin (that I happen to maintain), which will fall back to a minimal preview when JCEF is not available. There is a different preview JavaFX, which has been deprecated some time ago, so this is also not a good option, see https://blog.jetbrains.com/platform/2020/07/javafx-and-jcef-in-the-intellij-platform/

The recommendation I have is to use the JRE provided by JetBrains, that is: to switch to a different download in the spec file (`ideaIC-%{version}-no-jbr.tar.gz` -> `ideaIC-%{version}.gz`). The download without the JRE is no longer offered on the download page: https://www.jetbrains.com/idea/download/#section=linux
Also their docs point out to use the JetBrains JDK, see https://www.jetbrains.com/help/idea/switching-boot-jdk.html.

So I recommend to use the version of IntelliJ that bundles the JRE for a good user experience. 

I'll try to submit a patch and test this locally.

**Comment by themr0c** [comment]
That will be awesome! The COPR built for PyCharm already does this, and it's really a better user experience.
